### ISSUE TITLE
Build results unexpectedly return no test cases returned

### ISSUE THREAD

**Issue by acv111** [microsoft/nutter#70] opened 2022-02-24 22:35 UTC
While running a build in Azure DevOps, nutter is occassionally returning a result of: "No test cases were returned." and a lengthy encrypted string as the notebook output.  This generally can be resolved by rerunning the build, and seems to be inconsistent in its behavior.  The notebook output in the build step is similar to the output if you execute a test locally without commenting out result.exit(dbutils), except it is roughly 5x the length.

I can not consistently reproduce this behavior, and cannot reproduce when running the test notebook locally.  When running locally, the test cases within the notbook succeed without issue.

**Comment by giventocode** [comment] 2022-03-07 23:27
Sorry for the delayed response. Have you looked at the specific run id that when the issue occurs? The behavior you describe could be caused by a failure that returns a stack that the client can't deserialize. The next release will contain a fix for this. To get further details on the issue, you can enable debugging (--debug flag).

**Comment by giventocode** [comment] 2022-12-21 07:06
Closing the issue for lack of response and repro details.

**Closed by giventocode** 2022-12-21 07:06 UTC
